### ISSUE TITLE
Mobile layout broken

### ISSUE THREAD

**Issue by wohnout** [hslayers/cordova#2]
Mobile layout is broken after redesign of the main hslayers example.

Original at https://redmine.ccss.cz/issues/5456

**Comment by SLeitgeb** [comment]
Update: mobile layout is being fixed, so far buttons are not clickable. Upcoming solution expected to be more persistant.

**Comment by SLeitgeb** [comment]
New version of the mobile layout introduced in the latest commit. More tweaking soon to come.

**Comment by SLeitgeb** [comment]
Animated CSS transitions implemented for the side menu.

**Comment by SLeitgeb** [comment]
If the geolocation interface is active when the Search button is clicked, geolocation interface is hidden and vice versa. Introduced in the recent commit to improve user experience.
